### ISSUE TITLE
After pressing Enter in the Message field, the cursor is no longer in the Message field

### ISSUE THREAD

**Issue by FreakErn** [AugustDev/enchanted#161] opened 2024-10-27 14:10 UTC
As the title says, when i enter a Message, press enter, the Cursor disappears and the focus is no longer in the Message field and i have to use the Mouse to get to the Message field. 

I haven't found a shortcut to get back into that message field.

System MacOs Sequoia latest updates.

**Comment by AlekSi** [comment] 2024-12-21 18:21
Duplicate of #67

**Closed** 2024-12-21 20:06 UTC
