### ISSUE TITLE
Keyboard bug iOS

### ISSUE THREAD

**Issue by byt3magic** [AugustDev/enchanted#58] opened 2024-03-25 00:07 UTC
Hello, 

if you prompt anything and get a response from the system and you try to create a new session (button at the right top corner), then the keyboard of the iPhone 12 (latest iOS) is blocking/overlaying the text field and send button. Please fix that. Otherwise, it's a great app. 

Thank you.

**Comment by AugustDev** [comment] 2024-03-30 18:22
Hi @byt3magic would you be able to share a screenshot? I am not able to reproduce it on iPhone 12. Thank you!

**Comment by aniqueta** [comment] 2024-04-21 15:36
I have the same issue on iOS. 

To reproduce:
1. Start a new chat
2. Send prompt 
3. Receive response 
4. Begin typing reply prompt 
5. Tap new chat button 

Keyboard is still present covering half the interface. 

Thanks for a great app! Find it better than Open WebUI as the native interface is faster.

**Comment by AugustDev** [comment] 2024-04-29 12:52
Thank you for the steps @aniqueta. Fixed will be in next release later today!

**Closed by AugustDev** 2024-04-29 12:52 UTC
